#NAME: Xiwei Ma,Yunong Ye
#EMAIL: xiweimacn@163.com,yeyunong@hotmail.com
#ID: 704755732,004757414

default:
	chmod +x lab3b

clean:
	rm -f *.tar.gz

dist: lab3b-004757414.tar.gz
files = lab3b.py Makefile lab3b README

lab3b-004757414.tar.gz:
	tar -zcf $@ $(files)