#Name:Terry Ye
#Email: yeyunong@hotmail.com
#ID: 004757414

default:
	gcc -g -Wall -Wextra lab1a.c -o lab1a

clean:
	rm -f lab1a *.tar.gz

dist: clean
	tar -cvzf lab1a-004757414.tar.gz lab1a.c Makefile README
